// <auto-generated />
using System;
using Automation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Automation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406094306_AddFullSeedData")]
    partial class AddFullSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Automation.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SignDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Contracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContractNumber = "К-2020-001",
                            EmployeeId = 1,
                            IsActive = true,
                            Notes = "Бессрочный трудовой договор",
                            Salary = 150000m,
                            SignDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ContractNumber = "К-2020-002",
                            EmployeeId = 2,
                            IsActive = true,
                            Notes = "Бессрочный трудовой договор",
                            Salary = 80000m,
                            SignDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            ContractNumber = "К-2021-003",
                            EmployeeId = 3,
                            EndDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Notes = "Срочный трудовой договор на 3 года",
                            Salary = 90000m,
                            SignDate = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            ContractNumber = "К-2021-004",
                            EmployeeId = 4,
                            IsActive = true,
                            Notes = "Бессрочный трудовой договор",
                            Salary = 60000m,
                            SignDate = new DateTime(2021, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            ContractNumber = "К-2022-005",
                            EmployeeId = 5,
                            IsActive = true,
                            Notes = "Бессрочный трудовой договор",
                            Salary = 50000m,
                            SignDate = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = 0
                        });
                });

            modelBuilder.Entity("Automation.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Руководство компании",
                            Name = "Администрация"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Финансовый отдел",
                            Name = "Бухгалтерия"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Информационные технологии",
                            Name = "IT отдел"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Продажи и маркетинг",
                            Name = "Отдел продаж"
                        });
                });

            modelBuilder.Entity("Automation.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Series")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            IssueDate = new DateTime(2010, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuedBy = "ОВД Центрального района г. Москвы",
                            Number = "123456",
                            Series = "4510",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            IssueDate = new DateTime(2005, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuedBy = "ОВД Северного района г. Москвы",
                            Number = "234567",
                            Series = "4511",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            IssueDate = new DateTime(2014, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuedBy = "Московский Государственный Университет",
                            Number = "МГУ 2014-12345",
                            Type = 3
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 4,
                            IssueDate = new DateTime(2010, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuedBy = "ОВД Южного района г. Москвы",
                            Number = "345678",
                            Series = "4512",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 5,
                            IssueDate = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IssuedBy = "Учебный центр 1С",
                            Notes = "Сертификат 1С:Бухгалтерия",
                            Number = "CERT-2020-5678",
                            Type = 5
                        });
                });

            modelBuilder.Entity("Automation.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PassportNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PassportSeries")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IsActive");

                    b.HasIndex("LastName");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "г. Москва, ул. Ленина, д. 10",
                            BirthDate = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 1,
                            Email = "petrov@company.ru",
                            FirstName = "Иван",
                            HireDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastName = "Петров",
                            MiddleName = "Сергеевич",
                            Phone = "+7 (999) 123-45-67",
                            PositionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "г. Москва, ул. Пушкина, д. 5",
                            BirthDate = new DateTime(1985, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "ivanova@company.ru",
                            FirstName = "Мария",
                            HireDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastName = "Иванова",
                            MiddleName = "Петровна",
                            Phone = "+7 (999) 234-56-78",
                            PositionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "г. Москва, ул. Гагарина, д. 20",
                            BirthDate = new DateTime(1992, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 3,
                            Email = "smirnov@company.ru",
                            FirstName = "Алексей",
                            HireDate = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastName = "Смирнов",
                            MiddleName = "Дмитриевич",
                            Phone = "+7 (999) 345-67-89",
                            PositionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "г. Москва, ул. Мира, д. 15",
                            BirthDate = new DateTime(1990, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 4,
                            Email = "kozlova@company.ru",
                            FirstName = "Елена",
                            HireDate = new DateTime(2021, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastName = "Козлова",
                            MiddleName = "Александровна",
                            Phone = "+7 (999) 456-78-90",
                            PositionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "г. Москва, ул. Советская, д. 8",
                            BirthDate = new DateTime(1988, 7, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = 2,
                            Email = "novikov@company.ru",
                            FirstName = "Дмитрий",
                            HireDate = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LastName = "Новиков",
                            MiddleName = "Иванович",
                            Phone = "+7 (999) 567-89-01",
                            PositionId = 5
                        });
                });

            modelBuilder.Entity("Automation.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Requirements")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 150000m,
                            Name = "Директор",
                            Requirements = "Высшее образование, опыт руководства от 10 лет"
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 80000m,
                            Name = "Главный бухгалтер",
                            Requirements = "Высшее экономическое образование, опыт от 5 лет"
                        },
                        new
                        {
                            Id = 3,
                            BaseSalary = 90000m,
                            Name = "Программист",
                            Requirements = "Высшее техническое образование, знание C#/.NET"
                        },
                        new
                        {
                            Id = 4,
                            BaseSalary = 60000m,
                            Name = "Менеджер по продажам",
                            Requirements = "Опыт продаж от 2 лет, коммуникабельность"
                        },
                        new
                        {
                            Id = 5,
                            BaseSalary = 50000m,
                            Name = "Бухгалтер",
                            Requirements = "Среднее специальное образование, знание 1С"
                        });
                });

            modelBuilder.Entity("Automation.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Year", "Month");

                    b.ToTable("Salaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSalary = 150000m,
                            Bonus = 30000m,
                            Deductions = 23400m,
                            EmployeeId = 1,
                            IsPaid = true,
                            Month = 3,
                            Notes = "Премия за квартал",
                            PaymentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 0m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            BaseSalary = 80000m,
                            Bonus = 10000m,
                            Deductions = 11700m,
                            EmployeeId = 2,
                            IsPaid = true,
                            Month = 3,
                            Notes = "Стандартная выплата",
                            PaymentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 0m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            BaseSalary = 90000m,
                            Bonus = 15000m,
                            Deductions = 13650m,
                            EmployeeId = 3,
                            IsPaid = false,
                            Month = 3,
                            Notes = "Премия за проект",
                            PaymentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 0m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            BaseSalary = 60000m,
                            Bonus = 20000m,
                            Deductions = 10400m,
                            EmployeeId = 4,
                            IsPaid = false,
                            Month = 3,
                            Notes = "Премия за продажи",
                            PaymentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 0m,
                            Year = 2026
                        },
                        new
                        {
                            Id = 5,
                            BaseSalary = 50000m,
                            Bonus = 5000m,
                            Deductions = 7150m,
                            EmployeeId = 5,
                            IsPaid = true,
                            Month = 3,
                            Notes = "Стандартная выплата",
                            PaymentDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 0m,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Automation.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Администратор Системы",
                            IsActive = true,
                            Password = "admin123",
                            Role = 0,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "HR Менеджер",
                            IsActive = true,
                            Password = "hr123",
                            Role = 1,
                            Username = "hr"
                        });
                });

            modelBuilder.Entity("Automation.Models.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Vacations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            EndDate = new DateTime(2026, 7, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Ежегодный оплачиваемый отпуск",
                            StartDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            EndDate = new DateTime(2026, 8, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Ежегодный оплачиваемый отпуск",
                            StartDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            EndDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Больничный лист",
                            StartDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 4,
                            EndDate = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Ежегодный оплачиваемый отпуск",
                            StartDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Automation.Models.WorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AbsenceReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeSpan?>("CheckIn")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("CheckOut")
                        .HasColumnType("interval");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("EmployeeId");

                    b.ToTable("WorkSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckIn = new TimeSpan(0, 9, 0, 0, 0),
                            CheckOut = new TimeSpan(0, 18, 0, 0, 0),
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 1,
                            IsAbsent = false
                        },
                        new
                        {
                            Id = 2,
                            CheckIn = new TimeSpan(0, 9, 0, 0, 0),
                            CheckOut = new TimeSpan(0, 18, 0, 0, 0),
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 2,
                            IsAbsent = false
                        },
                        new
                        {
                            Id = 3,
                            CheckIn = new TimeSpan(0, 10, 0, 0, 0),
                            CheckOut = new TimeSpan(0, 19, 0, 0, 0),
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 3,
                            IsAbsent = false
                        },
                        new
                        {
                            Id = 4,
                            CheckIn = new TimeSpan(0, 9, 30, 0, 0),
                            CheckOut = new TimeSpan(0, 18, 30, 0, 0),
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 4,
                            IsAbsent = false
                        },
                        new
                        {
                            Id = 5,
                            AbsenceReason = "Больничный",
                            Date = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = 5,
                            IsAbsent = true
                        });
                });

            modelBuilder.Entity("Automation.Models.Contract", b =>
                {
                    b.HasOne("Automation.Models.Employee", "Employee")
                        .WithMany("Contracts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Automation.Models.Document", b =>
                {
                    b.HasOne("Automation.Models.Employee", "Employee")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Automation.Models.Employee", b =>
                {
                    b.HasOne("Automation.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Automation.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Automation.Models.Salary", b =>
                {
                    b.HasOne("Automation.Models.Employee", "Employee")
                        .WithMany("Salaries")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Automation.Models.Vacation", b =>
                {
                    b.HasOne("Automation.Models.Employee", "Employee")
                        .WithMany("Vacations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Automation.Models.WorkSchedule", b =>
                {
                    b.HasOne("Automation.Models.Employee", "Employee")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Automation.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Automation.Models.Employee", b =>
                {
                    b.Navigation("Contracts");

                    b.Navigation("Documents");

                    b.Navigation("Salaries");

                    b.Navigation("Vacations");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("Automation.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
